export const SCHEMAS_FOLDER = 'api-schemas'
export const TYPES_BANNER_COMMENT =
  '/* eslint-disable */\n/**\n* This file was automatically generated by openapi-handler.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file or OPEN API YML,\n* and run generate-types to regenerate this file.\n*/'
