/* eslint-disable */
/**
 * This file was automatically generated by api-handler. DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema
 * file or OPEN API YML, and run generate-types to regenerate this file.
 */

export type Baan = Baan1 & Baan2;
export type Baan1 = BaanBase;

export interface BaanBase {
  firstName: string;
  lastName: string;
  fathersName: string;
  address: string;
  nickName: string;
  amount: number;
}
export interface Baan2 {
  _id: string;
  BhaaiId?: string;
}
