/* eslint-disable */
/**
 * This file was automatically generated by api-handler. DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema
 * file or OPEN API YML, and run generate-types to regenerate this file.
 */

export interface BaanBase {
  firstName: string;
  lastName: string;
  fathersName: string;
  address: string;
  nickName: string;
  amount: number;
}
