/* eslint-disable */
/**
 * This file was automatically generated by api-handler. DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema
 * file or OPEN API YML, and run generate-types to regenerate this file.
 */

export type CustomerList = CustomerBase[];

export interface CustomerBase {
  email: string;
  phoneNumber?: string;
  password: string;
}
