/* eslint-disable */
/**
 * This file was automatically generated by api-handler. DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema
 * file or OPEN API YML, and run generate-types to regenerate this file.
 */

export type Customer = Customer1 & Customer2;
export type Customer1 = CustomerBase;

export interface CustomerBase {
  email: string;
  phoneNumber?: string;
  password: string;
}
export interface Customer2 {
  _id: string;
}
