/* eslint-disable */
/**
 * This file was automatically generated by api-handler. DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema
 * file or OPEN API YML, and run generate-types to regenerate this file.
 */

export type NimtaList = NimtaBase[];

export interface NimtaBase {
  name: string;
  relative: string[];
}
