/* eslint-disable */
/**
 * This file was automatically generated by api-handler. DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema
 * file or OPEN API YML, and run generate-types to regenerate this file.
 */

export type PariwarRole = PariwarRole1 & PariwarRole2;
export type PariwarRole1 = PariwarRoleBase;

export interface PariwarRoleBase {
  role: string;
  customerId?: string;
}
export interface PariwarRole2 {
  _id: string;
  pariwarId: string;
}
