/* eslint-disable */
/**
 * This file was automatically generated by api-handler. DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema
 * file or OPEN API YML, and run generate-types to regenerate this file.
 */

export type Pariwar = Pariwar1 & Pariwar2;
export type Pariwar1 = PariwarBase;
export type PariwarList = Pariwar[];

export interface PariwarBase {
  name: string;
}
export interface Pariwar2 {
  _id: string;
}
